# ===============================
# 預設啟用 dev Profile
# ===============================
spring.profiles.active=dev

# ===============================
# 共用設定（不分環境）
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.encoding=UTF-8
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always